//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonderaWebDevTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryData
    {
        public long Id { get; set; }
        public int Code { get; set; }
        public string CountryName { get; set; }
        public string CurrencyName { get; set; }
    }
}
